stages:
  - setup
  - dryrun
  - update
  - roll

variables:
  KOPS_CLUSTER_NAME: k8s.cmh.securesea.io

image: gitlab.securesea.io/devs/base_k8s/kops

dryrun:
  stage: dryrun
  only:
    - main@devs/base_k8s
  script:
    - kops replace --force -f clusters/cmh/k8s.cmh.securesea.io
    - kops update cluster

update:
  stage: update
  only:
    - main@devs/base_k8s
  when: manual
  script:
    - kops update cluster --yes
    - kops rolling-update cluster

roll:
  stage: roll
  only:
    - main@devs/base_k8s
  when: manual
  script:
    - kops rolling-update cluster --yes
