stages:
  - dryrun
  - update
  - roll

variables:
  KOPS_CLUSTER_NAME: k8s.cmh.securesea.io

image: alpine:edge

setup:
  stage: setup
  script:
    - curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
    - chmod +x kops-linux-amd64
    - mv kops-linux-amd64 /usr/local/bin/kops

dryrun:
  stage: dryrun
  only:
    - main@devs/base_k8s
  script:
    - kops replace --force -f clusters/cmh/k8s.cmh.securesea.io
    - kops update cluster

update:
  stage: update
  only:
    - main@devs/base_k8s
  when: manual
  script:
    - kops update cluster --yes
    - kops rolling-update cluster

roll:
  stage: roll
  only:
    - main@devs/base_k8s
  when: manual
  script:
    - kops rolling-update cluster --yes
