apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - argocd.questc.biz
    secretName: questc-wildcard-sec
  rules:
  - host: argocd.gps.aspect-cloud.net
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https