apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argo-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://argoproj.github.io/argo-helm
      insecureIgnoreHostKey: true
    - url: https://charts.jetstack.io
      insecureIgnoreHostKey: true
    - url: https://github.com/C0ntra99/base_k8s.git
      insecureIgnoreHostKey: true