apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argo-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://argoproj.github.io/argo-helm
      insecureIgnoreHostKey: true