apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  project: default
  source:
    path: charts/cert-manager
    repoURL: https://github.com/C0ntra99/base_k8s.git
    targetRevision: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true