apiVersion: v2
appVersion: 2.0.3
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 3.6.8
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: seanson
dependencies:
  - name: redis-ha
    version: 4.12.14
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.1
  configs:
    secret:
      argocdServerAdminPassword: "$2y$10$Fww5AfC6UZv5l9oYNFyx6Ocku8u3z.ne9sB0V0jiY0ev.Ow8bnie2"

